language: cpp
dist: trusty
sudo: required
branches:
  only:
  - master

jobs:
  include:
  - stage: test
    script:
    - ls -alh /usr/local/clang-5.0.0/lib
    - scons --test
    compiler: gcc
    env: COMPILER=g++-4.8
    addons:
      apt:
        update: true
        sources:
          - ubuntu-toolchain-r-test
          - sourceline: 'ppa:mhier/libboost-latest'
        packages:
          - boost1.67
          - g++-4.8
  - stage: Build docs
    # Nasty hack to get clang right
    before_install:
    - curl https://apt.llvm.org/llvm-snapshot.gpg.key | sudo apt-key add -
    - echo "deb http://apt.llvm.org/trusty/ llvm-toolchain-trusty-4.0 main" | sudo tee -a /etc/apt/sources.list
    - sudo apt-get update -qq
    - sudo apt-get install -y libclang1-4.0
    script:
    - scons
    - cd docs && make && cd ..
    compiler: gcc
    env: COMPILER=g++-4.8
    addons:
      apt:
        update: true
        sources:
          - ubuntu-toolchain-r-test
          - sourceline: 'ppa:mhier/libboost-latest'
        packages:
          - boost1.67
          - g++-4.8
    deploy:
      provider: pages
      skip_cleanup: true
      github_token: $GH_TOKEN
      local_dir: docs/site
      target_branch: gh-pages

install:
- export CXX=$COMPILER
- git clone https://github.com/astropy/ci-helpers.git
- source ci-helpers/travis/setup_conda_${TRAVIS_OS_NAME}.sh

env:
  global:
  - SETUP_XVFB=True
  - PYTHON_VERSION=3.6
  - NUMPY_VERSION='stable'
  - ASTROPY_VERSION='stable'
  - CONDA_DEPENDENCIES='matplotlib scons seaborn jinja2'
  - PIP_DEPENDENCIES='git+git://github.com/wtbarnes/cldoc.git@py3fix mkdocs mkdocs-material beautifulsoup4'
  - secure: fEC6R5e7+R/vcEY+Av7cWPUHVn2eKVRdrgPy2t9l4ja8op3OFL6gsMA4kUXmWfVT+kxwu7OfNzoId/2NQHoqNxGY3qV/dV+kE36xOy9go1aPTCfc2r5oZeWn8kDnoyBr8/hqO7LBMlpjgFGll+YVxm8YLmOFYxGI5JSeihAy2N7Lrs6V10OLFT3cnyWXMp40E/90G1he5RJbh+7KBtz2l82wDoqdVM+7mhEVdZLkVrpdcUGBY9UjVTTSO8Y0wYfAPi+HciFkJLKCbp76gQtjOVvSQTjZyBmHwJmpMXHO4NXhRQQn5uR4CLLCuv35YyijUGck1DUoLoSW70g8PuISOhdiEVeWZ6rp8gnK6a/XWIyhJhj8OwOdufFoYYVvSckmOy49uFmOZAGArNzYDPNRr3/wE6Crb1tScjJvTmcE57/qeUOidKqrRloS2n/evQEY3ES4HuVtb3gHWoQq1X9QqoeS0G3dAPwqJeEYzhDHEuDS5pPHbMaqnLHmvy/M3I8mqsGhTNloAsjvMwavKoCBnUkDpjHaGhGzTTq0qCVmkubekL+Op3s/bE39G4WRD6W61HGNoJIi/XGRiy6aPwjBOEJMgpmx9YQ1zAxmdEi78BEJfO2sGrL1X5ghT42IBiYz3eueYXl/2EcaDVzn/dn+3IA9YdiCgCWx0y3R44mbiKI=
