language: cpp
sudo: required
branches:
  only:
  - master

jobs:
  include:
  - stage: test
    script: scons --test
    #compiler: gcc
    env: CXX=g++-4.8
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
          - boost-latest
        packages:
          - libboost1.55-all-dev
          - g++-4.8
  - script: scons && cd docs && make && cd ..
    #compiler: clang
    env: 
      - CXX=clang++-3.4
      - CC=clang-3.4
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
          - boost-latest
        packages:
          - libboost1.55-all-dev
          - clang-3.4
  - stage: deploy
    script: ./deploy.sh
    compiler: clang
    env: CXX=clang-3.4
    if: type IS NOT pull_request
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
          - boost-latest
        packages:
          - libboost1.55-all-dev
          - clang-3.4

install:
- git clone https://github.com/astropy/ci-helpers.git
- source ci-helpers/travis/setup_conda_${TRAVIS_OS_NAME}.sh
#- git clone https://github.com/jessevdk/cldoc.git && cd cldoc && python setup.py install && cd ..

env:
  global:
  - SETUP_XVFB=True
  - CONDA_PREFIX=/home/travis/miniconda/envs/test
  - PYTHON_VERSION=2.7
  - NUMPY_VERSION='stable'
  - ASTROPY_VERSION='stable'
  - CONDA_DEPENDENCIES='matplotlib scons seaborn'
  - PIP_DEPENDENCIES='cldoc ghp-import'
  - secure: fEC6R5e7+R/vcEY+Av7cWPUHVn2eKVRdrgPy2t9l4ja8op3OFL6gsMA4kUXmWfVT+kxwu7OfNzoId/2NQHoqNxGY3qV/dV+kE36xOy9go1aPTCfc2r5oZeWn8kDnoyBr8/hqO7LBMlpjgFGll+YVxm8YLmOFYxGI5JSeihAy2N7Lrs6V10OLFT3cnyWXMp40E/90G1he5RJbh+7KBtz2l82wDoqdVM+7mhEVdZLkVrpdcUGBY9UjVTTSO8Y0wYfAPi+HciFkJLKCbp76gQtjOVvSQTjZyBmHwJmpMXHO4NXhRQQn5uR4CLLCuv35YyijUGck1DUoLoSW70g8PuISOhdiEVeWZ6rp8gnK6a/XWIyhJhj8OwOdufFoYYVvSckmOy49uFmOZAGArNzYDPNRr3/wE6Crb1tScjJvTmcE57/qeUOidKqrRloS2n/evQEY3ES4HuVtb3gHWoQq1X9QqoeS0G3dAPwqJeEYzhDHEuDS5pPHbMaqnLHmvy/M3I8mqsGhTNloAsjvMwavKoCBnUkDpjHaGhGzTTq0qCVmkubekL+Op3s/bE39G4WRD6W61HGNoJIi/XGRiy6aPwjBOEJMgpmx9YQ1zAxmdEi78BEJfO2sGrL1X5ghT42IBiYz3eueYXl/2EcaDVzn/dn+3IA9YdiCgCWx0y3R44mbiKI=
